#cargo-features = ["strip"]

[workspace]

members =[
    "tor",
    "utils",
    "sifir-android",
    "sifir-ios"
]

[profile.dev]
opt-level = "s"

[profile.release]
opt-level="z"
lto = true
codegen-units = 1 
#strip = "symbols"

