[package]
name = "sifir-ios"
version = "0.1.0"
authors = ["Gus Abidi <gabidi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tor = { path = "../tor" }
cargo-lipo = "3.1.1"

[build-dependencies]
cbindgen = "0.15.0"

[lib]
crate-type = ["staticlib", "cdylib"]