// Automatically generated by flapigen
package com.sifir.sdk;
import android.support.annotation.NonNull;

public final class OwnedTorService {

    public OwnedTorService(@NonNull TorServiceParam param) {
        long a0 = param.mNativeObj;
        param.mNativeObj = 0;

        mNativeObj = init(a0);
        JNIReachabilityFence.reachabilityFence1(param);
    }
    private static native long init(long param);

    public final void shutdown() {
        do_shutdown(mNativeObj);
    }
    private static native void do_shutdown(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ OwnedTorService(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}