// Automatically generated by flapigen
package com.sifir.sdk;
import android.support.annotation.NonNull;

public final class TorServiceParam {

    private TorServiceParam() {}

    public final @NonNull String getDataDir() {
        String ret = do_getDataDir(mNativeObj);

        return ret;
    }
    private static native @NonNull String do_getDataDir(long self);

    public final @NonNull String getSockPort() {
        String ret = do_getSockPort(mNativeObj);

        return ret;
    }
    private static native @NonNull String do_getSockPort(long self);

    public final @NonNull String getPort() {
        String ret = do_getPort(mNativeObj);

        return ret;
    }
    private static native @NonNull String do_getPort(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ TorServiceParam(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}