[package]
name = "tor"
version = "0.1.0"
authors = ["Gus Abidi <gabidi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version="0.10.8", features = ["socks", "json"] }
tokio = { version= "0.2", features = ["full"] }
libtor = {version= "44.5.2+0.4.4.5", features=["vendored-openssl"]}
torut = { version = "0.1.6" , features=["vendored_openssl"] }
anyhow = "1.0.33"
serde = { version="1.0.117", features = ["derive"]}
lazy_static = "1.4.0"
futures = "0.3.8"

[dev-dependencies]
serial_test = "*"

[lib]
crate-type = ["staticlib", "cdylib"]
#crate-type = ["lib", "cdylib"]
