// Automatically generated by flapigen
package com.sifir.tor;


public final class DerivedBip39Xprvs {

    public static native String descriptors_from_xprvs_wpaths_vec(String vec_xprvs_with_paths_json, String network) throws Exception;

    private DerivedBip39Xprvs() {}
}