// Automatically generated by flapigen
package com.sifir.tor;


public final class ElectrumSledWallet {

    public ElectrumSledWallet(String wallet_cfg_json) throws Exception {
        mNativeObj = init(wallet_cfg_json);
    }
    private static native long init(String wallet_cfg_json) throws Exception;

    public final long get_balance() throws Exception {
        long ret = do_get_balance(mNativeObj);

        return ret;
    }
    private static native long do_get_balance(long self) throws Exception;

    public final String get_new_address() throws Exception {
        String ret = do_get_new_address(mNativeObj);

        return ret;
    }
    private static native String do_get_new_address(long self) throws Exception;

    public final void sync(long max_address_count) throws Exception {
        do_sync(mNativeObj, max_address_count);
    }
    private static native void do_sync(long self, long max_address_count) throws Exception;

    public final String create_tx(String tx) throws Exception {
        String ret = do_create_tx(mNativeObj, tx);

        return ret;
    }
    private static native String do_create_tx(long self, String tx) throws Exception;

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ ElectrumSledWallet(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}