// Automatically generated by flapigen
package com.sifir.tor;


public final class TcpSocksStream {

    public TcpSocksStream(String target, String socks_proxy, long timeout_ms) {
        mNativeObj = init(target, socks_proxy, timeout_ms);
    }
    private static native long init(String target, String socks_proxy, long timeout_ms);

    public final void on_data(DataObserver cb) {
        do_on_data(mNativeObj, cb);
    }
    private static native void do_on_data(long self, DataObserver cb);

    public final void send_data(String msg, long timeout) {
        do_send_data(mNativeObj, msg, timeout);
    }
    private static native void do_send_data(long self, String msg, long timeout);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ TcpSocksStream(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}