// Automatically generated by flapigen
package com.sifir.tor;


public final class TorHiddenService {

    private TorHiddenService() {}

    public final HiddenServiceHandler start_http_handler(int dst_port, DataObserver cb) throws Exception {
        long ret = do_start_http_handler(mNativeObj, dst_port, cb);
        HiddenServiceHandler convRet = new HiddenServiceHandler(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_start_http_handler(long self, int dst_port, DataObserver cb) throws Exception;

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ TorHiddenService(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}