// Automatically generated by flapigen
package com.sifir.tor;


public final class TorHiddenService {

    private TorHiddenService() {}

    public final String get_onion_url() {
        String ret = do_get_onion_url(mNativeObj);

        return ret;
    }
    private static native String do_get_onion_url(long self);

    public final String get_secret_b64() {
        String ret = do_get_secret_b64(mNativeObj);

        return ret;
    }
    private static native String do_get_secret_b64(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ TorHiddenService(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}