// Automatically generated by flapigen
package com.sifir.tor;


public final class TorServiceParam {

    public TorServiceParam(String data_dir, int socks_port, long bootstap_timeout_ms) {
        mNativeObj = init(data_dir, socks_port, bootstap_timeout_ms);
    }
    private static native long init(String data_dir, int socks_port, long bootstap_timeout_ms);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ TorServiceParam(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}