// Automatically generated by flapigen
package com.sifir.tor;


public final class TorServiceParam {
    static {
        System.loadLibrary("sifir_android");
    }
    public TorServiceParam(String data_dir, int socks_port) {
        mNativeObj = init(data_dir, socks_port);
    }
    private static native long init(String data_dir, int socks_port);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ TorServiceParam(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}