[package]
name = "sifir-android"
version = "0.1.0"
authors = ["Gus Abidi <gabidi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tor = { path = "../tor" }
utils = { path="../utils" }
jni = "0.18.0"

[build-dependencies]
flapigen = "0.6.0-pre7"

[lib]
crate-type = ["staticlib", "cdylib"]
