[package]
name = "sifir-android"
version = "0.1.0"
authors = ["Gus Abidi <gabidi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tor = { path = "../tor" }
jni = "0.18.0"
jni-sys = "0.3.0"
log = "0.4.6"
log-panics = "2.0"
# TODO update 0.9 this if it doesn't nbreak anything
android_logger = "0.8"

[build-dependencies]
flapigen = "0.6.0-pre7"

[lib]
crate-type = ["staticlib", "cdylib"]
